huaxi/Areas/Admin/Controllers/DocumentController.cs
using huaxi.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;

namespace huaxi.Areas.Admin.Controllers
{
    [Authorize(Roles = "1")]
    public class DocumentController : Controller
    {
        //1.校内新闻
        //2.专卖推送
        //3.公告栏
        static int[] typeArr = { 1, 2, 3 };

        public ActionResult Index(int type = 1, int page = 1, string title = null, int status = 0)
        {
            List<string> ListWhere = new List<string>();
            string typeStr;
            string titleStr;
            string statusStr = "Status>-1";

            //查询删除的内容
            if (status == -1)
            {
                statusStr = "Status=-1";
                typeStr = "CateID in (" + string.Join(",", typeArr) + ")";
            }
            else
            {
                if (Array.IndexOf(typeArr, type) < 0)
                    type = typeArr[0];

                typeStr = "CateID=" + type;
            }

            ListWhere.Add(typeStr);
            ListWhere.Add(statusStr);

            if (title != null)
            {
                titleStr = string.Format("Title like '%{0}%'", title);
                ListWhere.Add(titleStr);
            }
            ViewBag.wd = title;
            string[] arrWhere = ListWhere.ToArray();
            IEnumerable<ViewArticle> List = ViewArticleDAL.ListByPage(page, 10, "UpdateTime", true, arrWhere);
            ViewBag.Count = ViewArticleDAL.ListCount(arrWhere);
            ViewBag.PageCount = ViewBag.Count / 10 + 1;
            ViewBag.StartNum = page * 10 - 9;
            ViewBag.EndNum = page * 10 < ViewBag.Count ? page * 10 : ViewBag.Count;
            ViewBag.Page = page;
            return View(List);

        }

        public ActionResult Create(int type = 1)
        {
            if (Array.IndexOf(typeArr, type) < 0)
                type = typeArr[0];
            try
            {
                ArticleModel model = new ArticleModel();
                model.Document = new DocumentModel();
                model.Document.CateID = type;
                model.Document.UserName = User.Identity.Name;
                return View(model);
            }
            catch
            {
                return RedirectToAction("Login", "Account");
            }
        }

        //添加[新闻]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ArticleModel model, int type = 1)
        {
            string msg = "";
            if (Array.IndexOf(typeArr, type) < 0)
                type = typeArr[0];
            if (ModelState.IsValid && ArticleBLL.Insert(model, out msg))
            {
                return RedirectToAction("Index", new { type = type });
            }
            else
            {
                ModelState.AddModelError("", msg);
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            ArticleModel model = ArticleBLL.GetById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ArticleModel model)
        {
            string msg = "";
            if (ModelState.IsValid && ArticleBLL.Update(model, out msg))
            {
                return RedirectToAction("Index", new { type = model.Document.CateID });
            }
            else
            {
                ModelState.AddModelError("", msg);
                return View();
            }
        }

        public ActionResult Delete(string[] id, int status = -1, int type = 1)
        {
            if (Array.IndexOf(typeArr, type) < 0)
                type = typeArr[0];
            if (id != null && id.Length > 0)
            {
                foreach (string i in id)
                {
                    ArticleBLL.Delete(Convert.ToInt32(i), status);
                }

            }
            return RedirectToAction("Index", new { type = type });
        }

        //彻底删除
        public ActionResult Destroy(string[] id)
        {
            if (id != null && id.Length > 0)
            {
                foreach (string i in id)
                {
                    ArticleBLL.Destroy(Convert.ToInt32(i));
                }
            }
            return RedirectToAction("Index", new { status = -1 });
        }
    }
}

huaxi/Areas/Admin/Controllers/StudyController.cs
using huaxi.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace huaxi.Areas.Admin.Controllers
{
    [Authorize(Roles = "1")]
    public class StudyController : Controller
    {

        //7.就业指导
        //9.资源共享
        //10.培训信息
        int[] typeArr = { 7, 9, 10 };
        public ActionResult Index(int type = 0, int page = 1, string title = null, int status = 0)
        {
            GetCateList();
            List<string> ListWhere = new List<string>();
            string typeStr;
            string titleStr;
            string statusStr = "Status>-1";
            if (status == -1)
            {
                statusStr = "Status=-1";
            }
            else {
                typeStr = "CateID=" + type;
                ListWhere.Add(typeStr);
            }
            ListWhere.Add(statusStr);
            if (title != null)
            {
                titleStr = string.Format("Title like '%{0}%'", title);
                ListWhere.Add(titleStr);
            }
            ViewBag.wd = title;
            string[] arrWhere = ListWhere.ToArray();
            IEnumerable<ViewArticle> List = ViewArticleDAL.ListByPage(page, 10, "UpdateTime", true, arrWhere);
            ViewBag.Count = ViewArticleDAL.ListCount(arrWhere);
            ViewBag.PageCount = ViewBag.Count / 10 + 1;
            ViewBag.StartNum = page * 10 - 9;
            ViewBag.EndNum = page * 10 < ViewBag.Count ? page * 10 : ViewBag.Count;
            ViewBag.Page = page;
            return View(List);
        }
        /// <summary>
        /// 分类管理
        /// </summary>
        /// <param name="status"></param>
        /// <returns></returns>
        public ActionResult CateManage(int status = 0)
        {
            GetCateList();
            GetCateList(status, 1);
            ViewBag.Cate = CategoryModel.ListCateByID(8).ToList();
            return View();
        }
        /// <summary>
        /// 获得分类列表
        /// </summary>
        /// <param name="status"></param>
        /// <param name="type"></param>
        private void GetCateList(int status = 0, int type = 0)
        {
            if (type == 1)
            {
                ViewBag.ListGuideCate = CategoryModel.ListCateByID(typeArr[0], status).ToList();
                ViewBag.ListShareCate = CategoryModel.ListCateByID(typeArr[1], status).ToList();
                ViewBag.ListTrainningCate = CategoryModel.ListCateByID(typeArr[2], status).ToList();
                return;
            }
            ViewBag.GuideCate = CategoryModel.ListCateByID(typeArr[0], status).ToList();
            ViewBag.ShareCate = CategoryModel.ListCateByID(typeArr[1], status).ToList();
            ViewBag.TrainningCate = CategoryModel.ListCateByID(typeArr[2], status).ToList();
        }
        /// <summary>
        /// 渲染添加学习视图
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult Create(int type = 0)
        {
            GetCateList();
            if (type == 0)
            {
                List<Category> ls1 = (List<Category>)ViewBag.GuideCate;
                ls1.AddRange((List<Category>)ViewBag.ShareCate);
                ls1.AddRange((List<Category>)ViewBag.TrainningCate);
                if (ls1.Count > 0)
                {
                    type = ls1[0].ID;
                }
                else {
                    ArticleModel model = null;
                    return View(model);
                }
            }
            try
            {
                ArticleModel model = new ArticleModel();
                model.Document = new DocumentModel();
                model.Document.CateID = type;
                model.Document.UserName = User.Identity.Name;
                return View(model);
            }
            catch
            {
                return RedirectToAction("Login", "Account");
            }
        }
        /// <summary>
       /// 添加[学习]
        /// </summary>
        /// <param name="model"></param>
        /// <param name="type"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(ArticleModel model, int type)
        {
            string msg = "";
            if (ModelState.IsValid && ArticleBLL.Insert(model, out msg))
            {
                return RedirectToAction("Index", new { type = type });
            }
            else
            {
                ModelState.AddModelError("", msg);
                GetCateList();
                return View();
            }
        }

        public ActionResult Delete(string[] id, int status = -1, int type=0)
        {
            if (id != null && id.Length > 0)
            {
                foreach (string i in id)
                {
                    ArticleBLL.Delete(Convert.ToInt32(i), status);
                }

            }
            return RedirectToAction("Index", new { type = type });
        }
        public ActionResult Destroy(string[] id)
        {
            if (id != null && id.Length > 0)
            {
                foreach (string i in id)
                {
                    ArticleBLL.Destroy(Convert.ToInt32(i));
                }
            }
            return RedirectToAction("Index", new { status = -1 });
        }

        /// <summary>
        /// 渲染编辑文章view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            GetCateList();
            ArticleModel model = ArticleBLL.GetById(id);
            return View(model);
        }
        /// <summary>
        /// 编辑文章
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(ArticleModel model)
        {
            string msg = "";
            if (ModelState.IsValid && ArticleBLL.Update(model, out msg))
            {
                return RedirectToAction("Index", new { type = model.Document.CateID });
            }
            else
            {
                ModelState.AddModelError("", msg);
                GetCateList();
                return View();
            }
        }
        /// <summary>
        /// 增加或修改分类
        /// </summary>
        /// <param name="model"></param>
        /// <param name="modif"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveCate(Category model, string modif = "add")
        {
            modif = modif.Trim();
            string msg = "";
            model.Status = 0;
            int st = 0;
            if (modif == "add") { st = CategoryBLL.Insert(model, ref msg) ? 1 : 0; }
            else if (modif == "update")
            {
                var ls = (List<Category>)CategoryDAL.ListByWhere(model, null, "Name");
                ls = ls.Where(a => a.ID != model.ID).ToList();
                if (ls.Count >= 1)
                {
                    return Json(new { status = 0, info = "标识已存在" });
                }
                st = CategoryDAL.Update(model) ? 1 : 0;
                if (st == 0) { msg = "保存失败"; }
            }
            else
            {
                st = 0; msg = "缺少操作参数";
            }
            return Json(new { status = st, info = msg });
        }
        /// <summary>
        /// 删除或回复分类
        /// </summary>
        /// <param name="id"></param>
        /// <param name="status"></param>
        /// <returns></returns>
        public ActionResult DeleteCate(string[] id, int status = -1)
        {
            if (id != null && id.Length > 0)
            {
                foreach (string i in id)
                {
                    CategoryBLL.Delete(Convert.ToInt32(i), status);
                }
            }
            return RedirectToAction("CateManage");
        }
        /// <summary>
        /// 彻底删除
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DestroyCate(string[] id)
        {
            if (id != null && id.Length > 0)
            {
                foreach (string i in id)
                {
                    CategoryBLL.Destroy(Convert.ToInt32(i));
                }
            }
            return RedirectToAction("CateManage", new { status = -1 });
        }
        /// <summary>
        /// ajax 获取分类数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetCateById(int id)
        {
            return Json(CategoryDAL.GetById(id));
        }
    }
}

huaxi/Areas/Admin/Views/Study/CateManage.cshtml
@{
    ViewBag.Title = "学习信息列表";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_StudyLayout")
<div class="col-md-9">
    <div class="panel panel-info">
        <div class="panel-heading">

            @if (Convert.ToInt32(HttpContext.Current.Request["status"]) == -1)
            {
                <div class="btn-group">
                    <button class="btn btn-danger ajax-post confirm" target-form="id" url="@Url.Action("DestroyCate")"><i class="icon-trash icon-white"></i>&nbsp彻底删除</button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-info ajax-post confirm" target-form="id" url="@Url.Action("DeleteCate",  new { status = 0 })"><i class="icon-ok-sign icon-white"></i>&nbsp恢复</button>
                </div>
            }
            else
            {

                <div class="btn-group">
                    <button class="btn btn-success addcate" title="添加分类">添加分类</button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-danger ajax-post confirm" target-form="id" url="@Url.Action("DeleteCate", "Study", new { type = @HttpContext.Current.Request["type"] })">
                        删除分类
                    </button>
                </div>
            }

        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr role="row">
                        <th style="width: 10px">
                            <input class="check-all" type="checkbox">
                        </th>
                        <th>编号</th>
                        <th>父分类</th>
                        <th>标题</th>
                        <th>标识</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody aria-relevant="all" aria-live="polite" role="alert">
                    @foreach (var v in ViewBag.ListGuideCate)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="id" class="id" value="@v.ID">
                            </td>
                            <td>@v.ID</td>
                            <td>就业指导</td>
                            <td>@v.Display</td>
                            <td>@v.Name</td>
                            <td>
                                @if (Convert.ToInt32(Request["status"]) != -1)
                                {
                                    <button class="btn btn-info editbtn" url="@Url.Action("GetCateById", new { id = @v.ID })">
                                        编辑
                                    </button>
                                }
                            </td>
                        </tr>
                    }
                    @foreach (var v in ViewBag.ListShareCate)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="id" class="id" value="@v.ID">
                            </td>
                            <td>@v.ID</td>
                            <td>资源共享</td>
                            <td>@v.Display</td>
                            <td>@v.Name</td>
                            <td>
                                @if (Convert.ToInt32(Request["status"]) != -1)
                                {
                                    <button class="btn btn-info editbtn" url="@Url.Action("GetCateById", new { id = @v.ID })">
                                        编辑
                                    </button>
                                }
                            </td>
                        </tr>
                    }  @foreach (var v in ViewBag.ListTrainningCate)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="id" class="id" value="@v.ID">
                            </td>
                            <td>@v.ID</td>
                            <td>培训信息</td>
                            <td>@v.Display</td>
                            <td>@v.Name</td>
                            <td>
                                @if (Convert.ToInt32(Request["status"]) != -1)
                                {
                                    <button class="btn btn-info editbtn" url="@Url.Action("GetCateById", new { id = @v.ID })">
                                        编辑
                                    </button>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- 添加分类modal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title hightlight" id="addModalLabel">添加分类</h4>
            </div>
            <form id="cateform" class="form-horizontal" action="@Url.Action("SaveCate")" method="post" onsubmit="return ajaxsubmit()">
                <input type="hidden" value="" id="ID" name="ID" />
                <input type="hidden" value="add" id="modif" name="modif" />
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">父分类</label>
                        <div class="col-sm-10">
                            <select class="form-control none-radius" id="PID" name="PID">
                                @foreach (var v in ViewBag.Cate)
                                {
                                    <option value="@v.ID">@v.Display</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">标题</label>
                        <div class="col-sm-10">
                            <input type="text" name="Display" id="Display" class="form-control none-radius" placeholder="标题" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">标识</label>
                        <div class="col-sm-10">
                            <input type="text" name="Name" id="Name" class="form-control none-radius" placeholder="标识" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                    <button id="submitaddress" type="submit" class="btn btn-primary" data-loading-text="提交中..." autocomplete="off">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>
@section Js{
    <script>
        $(function () {
            $('.addcate').click(function () {
                $('#addModalLabel').html('添加分类');
                $('#modif').val('add');
                $('#addModal').find('input[name="ID"]').val('');
                $('#addModal').modal('show');
            });
            $('.editbtn').click(function () {
                var _url = $(this).attr('url');
                ajaxget(_url, setmodal);
            });

        });
        function setmodal(data) {
            if (!data) {
                showerrormsg('网络连接失败', 100, 1000);
                return false;
            }
            $('#addModalLabel').html('编辑分类');
            $('#modif').val('update');
            $('#addModal').find('input[name="ID"]').val(data.ID);
            $('#Display').val(data.Display);
            $('#Name').val(data.Name);
            $('#addModal').modal('show');
            $('#PID').find('option').each(function () {
                if (parseInt($(this).val() == parseInt(data.PID))) {
                    $(this).attr('selected', 'selected');
                    return true;
                }
            });
        }
        function ajaxget(_url, reback) {
            $.ajax({
                type: 'post',
                url: _url,
                beforeSend: function () {
                    loading();
                },
                error: function (request) {
                    showerrormsg('网络连接失败', 100, 1000);
                    return null;
                }, success: function (data) {
                    return reback(data);
                },
                complete: function () {
                    $("#load").remove();
                }
            });
        }
        //异步提交表单
        function ajaxsubmit() {
            var form = $("form");
            var $btn = form.find('button[type="submit"]').button('loading');
            $.ajax({
                type: form.attr("method"),
                url: form.attr("action"),
                data: form.serialize(),
                beforeSend: function () {
                    loading();
                },
                error: function (request) {
                    showerrormsg('网络连接失败', 100, 1000);
                    $btn.button('reset');
                },
                success: function (data) {
                    if (data.status != 1) {
                        showerrormsg(data.info, 100, 1000);
                    }
                    else {
                        showsuccessmsg('操作成功', 100, 1000);
                        form[0].reset();
                        $('#addModal').modal('hide');
                        setTimeout(function () {
                            window.location.href = window.location.href;
                        }, 300);
                    }
                },
                complete: function () {
                    $("#load").remove();
                    $btn.button('reset');
                }
            });
            return false;
        }
    </script>
}

huaxi/Areas/Admin/Views/Study/Create.cshtml
@model huaxi.Areas.Admin.Models.ArticleModel

@{
    ViewBag.Title = "添加学习";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@if (Model == null) { 
    <script>
        alert("没有可用的分类，请先创建分类！");
        window.location.href = "@Url.Action("CateManage")";
    </script>
}
@Html.Partial("_StudyLayout")
<div class="col-md-9">
    <div class="panel panel-success">
        <div class="panel-heading">
            @ViewBag.Title 作者:@User.Identity.Name
            <a href="@Url.Action("Index", new { type = @HttpContext.Current.Request["type"] })" type="button">&nbsp;&nbsp;返回</a>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(m => m.Document.CateID)
                @Html.HiddenFor(m => m.Document.UserName)
                @Html.Hidden("type")
                <div class="modal-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Document.Title, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Document.Title, new { @class = "form-control none-radius", required = "required" })
                        @Html.ValidationMessageFor(model => model.Document.Title)
                    </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.BeFrom, new { @class = "" })
                            @Html.TextBoxFor(model => model.BeFrom, new { @class = "form-control none-radius" })
                            @Html.ValidationMessageFor(model => model.BeFrom)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Document.Description, new { @class = "" })
                            @Html.TextAreaFor(model => model.Document.Description, new { @class = "form-control none-radius" })
                            @Html.ValidationMessageFor(model => model.Document.Description)
                        </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Contents, new { @class = "" })
                        @Html.TextAreaFor(model => model.Contents, new { @class = "form-control none-radius", style = "height:300px" })
                        @Html.ValidationMessageFor(model => model.Contents)
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">发布</button>
                    <button type="reset" class="btn btn-danger">重置</button>
                </div>
            }
        </div>
    </div>
</div>
<script src="~/Content/Scripts/kindeditor/kindeditor-min.js"></script>
<script src="~/Content/Scripts/kindeditor/lang/zh_CN.js"></script>
@section Js{
    <script src="~/Content/Scripts/KindEditor.js"></script>
}

huaxi/Areas/Admin/Views/Study/Edit.cshtml
@model huaxi.Areas.Admin.Models.ArticleModel

@{
    ViewBag.Title = "添加学习";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_StudyLayout")
<div class="col-md-9">
    <div class="panel panel-success">
        <div class="panel-heading">
            @ViewBag.Title 作者:@User.Identity.Name
            <a href="@Url.Action("Index", "Document", new { type = @HttpContext.Current.Request["type"] })" type="button">&nbsp;&nbsp;返回</a>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(m => m.Document.ID)
                @Html.HiddenFor(m => m.Document.CateID)
                <div class="modal-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Document.Title, new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.Document.Title, new { @class = "form-control none-radius", required = "required" })
                        @Html.ValidationMessageFor(model => model.Document.Title)
                    </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.BeFrom, new { @class = "" })
                            @Html.TextBoxFor(model => model.BeFrom, new { @class = "form-control none-radius" })
                            @Html.ValidationMessageFor(model => model.BeFrom)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Document.Description, new { @class = "" })
                            @Html.TextAreaFor(model => model.Document.Description, new { @class = "form-control none-radius" })
                            @Html.ValidationMessageFor(model => model.Document.Description)
                        </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Contents, new { @class = "" })
                        @Html.TextAreaFor(model => model.Contents, new { @class = "form-control none-radius", style = "height:300px" })
                        @Html.ValidationMessageFor(model => model.Contents)
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">
                        发布
                    </button>
                    <button type="reset" class="btn btn-danger">
                        重置
                    </button>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Content/Scripts/kindeditor/kindeditor-min.js"></script>
<script src="~/Content/Scripts/kindeditor/lang/zh_CN.js"></script>
@section Js{
    <script src="~/Content/Scripts/KindEditor.js"></script>
}